### ISSUE TITLE
Genesis

### ISSUE THREAD

**Issue by nebgnahz** [nebgnahz/style-guess#1]
# Goal

Create a style test like [George Street Photo](www.georgestreetphoto.com) but for wedding (LadyMarry).

# Tasks
- [x] React project setup
- [x] Design data structure for application state
- [x] Finish all components in Javascript
- [x] Code Initial layout
- [x] Add gesture (see #2)
- [x] Make it PWA
- [x] Refine CSS
- [x] Deploy to Netlify
- [x] Take screenshot and declare success (see #4 )
